### PR TITLE
ArrayAccess for presenters and serialization with models

### PR DESCRIPTION
**Pull request by aronduby**
Created traits that gives ArrayAccess compatibility for presenters and another for models to add presenter data to their serialized data. This allows for the use of presenter data within queued jobs like Mail:queue

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You should have really asked me before creating a PR. I don't want to handle this as I don't think it's needed.

**Comment by GrahamCampbell** [comment]
I would strongly recommend that you DO NOT present an object and then put it in the queue.

**Comment by GrahamCampbell** [comment]
You should present it at the other end.

**Comment by aronduby** [comment]
I'd never heard of anyone asking permission to make a pull request, sorry that I've offended you with that. I figured your code was the closest that I could find to doing what I needed so I built off of that, and in a way where literally none of your code was touched. Figured since I had to fork and branch for it to work with my composer override I might as well click the PR button. But if you don't want it no harm no foul. Thanks for the great starting point.

There's 2 specific things I needed to be able to accomplish which this did. I would be very interested to hear how you would handle them because as of right now I'm not seeing a better way, but I'm also still a bit of a Laravel noob. 

1. Including presented values in queued mail jobs using redis as the driver. There will probably other jobs eventually but currently just mail.

2. Including presented values in events broadcasted through redis pubsub, node, and socket.io

At some point in the near future I'll also be returning models to be converted to json for use within an API which would also fail since it's the same basic concept as the 2 issues I'm working on right now.

**Comment by GrahamCampbell** [comment]
> I'd never heard of anyone asking permission to make a pull request, sorry that I've offended you with that. 

That wasn't the reason at all. It would have just prevent you from putting all this effort in only to find that I don't actually like the concept.

**Pull request closed without merging**
